# This workflow does static verification of the DafnyCore library
name: Dafny Core verification

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-examples-in-docs:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        # nightly-latest to catch anything that breaks these tests in current development
        # 2/18/2023 version is the first that supports logging
        # 3.11.0 supports new CLI but does not support logging
        version: [nightly-2023-02-18-ef4f346, 3.11.0, 3.12.0 ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.0
        with:
          dafny-version: ${{ matrix.version }}

      - name: Version information
        run: |
          dafny --version
          echo ${{ matrix.os }} ${{ runner.os }} ${{ matrix.version }}

      - name: Upgrade outdated pip
        run: python -m pip install --upgrade pip

      - name: Install lit
        run: pip install lit OutputCheck

      - name: Set up JS dependencies
        run: npm install bignumber.js

      - name: Verify Code and Examples
        run: |
          ./Scripts/check-examples `find . -name '*.md'`
