name: Checking examples in library documentation

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-examples-in-docs:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        version: [ 3.13.1, 4.0.0 ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.1
        with:
          dafny-version: ${{ matrix.version }}

      - name: Version information
        run: |
          dafny --version
          echo ${{ matrix.os }} ${{ runner.os }} ${{ matrix.version }}

      - name: Set up JS dependencies
        run: npm install bignumber.js

      - name: Verify Code and Examples
        run: |
          ./Scripts/check-examples `find . -name '*.md'`
