name: 'Generate Test Report'
on:
  workflow_run:
    workflows: ['tests']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: verification-results
        name: Verification Results
        path: '*.trx'
        reporter: dotnet-trx