name: Nightly Dafny Core verification

on:
  # Scheduled to be run sometime after the nightly build of dafny
  schedule:
    - cron: "7 10 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verification:
    strategy:
      matrix:
        # nightly-latest to catch anything that breaks these tests in current development
        # 2/18/2023 version is the first that supports logging, but it is not supported by setup-dafny-action 1.6.1
        # 3.11.0 supports new CLI but does not support logging
        # setup-dafny-action does not yet support 3.13.1 or recent nightly-lates

        version: [ nightly-latest, nightly-2023-02-18-ef4f346, 3.11.0, 3.12.0, 3.13.1, 4.0.0 ]

    uses: ./.github/workflows/reusable-tests.yml
    with:
      dafny-version: ${{ matrix.version }}
