# This workflow does static verification of the DafnyCore library
name: Reusable Dafny Core verification

on:
  workflow_call:

jobs:
  reusable_verification:
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.0
        with:
          dafny-version: 3.11.0
          ##dafny-version: ${{ inputs.dafny_version }}

      - name: Version information
        run: |
          dafny --version
          echo ${{ inputs.os }} ${{ runner.os }} 

      - name: Upgrade outdated pip
        run: python -m pip install --upgrade pip

      - name: Install lit
        run: pip install lit OutputCheck

      - name: Set up JS dependencies
        run: npm install bignumber.js

      - name: Verify Code and Examples without logging
        id: nolog
        if: inputs.dafny-version == '3.11.0'
        run: lit --time-tests -v .

      - name: Verify Code and Examples
        id: withlog
        if: steps.nolog.conclusion == 'skipped'
        run: |
          lit --time-tests -v --param 'dafny_params=--log-format trx --log-format csv' .

      - name: Generate Report
        if: always() && steps.withlog.conclusion != 'skipped'
        run: find . -name '*.csv' -print0 | xargs -0 --verbose dafny-reportgenerator summarize-csv-results --max-duration-seconds 10

      - uses: actions/upload-artifact@v2  # upload test results
        if: always() && steps.withlog.conclusion != 'skipped'
        with:
          name: verification-results
          path: '**/TestResults/*.trx'
          if-no-files-found: error
